### PR TITLE
Removed link to pfefferneuse

### PR DESCRIPTION
**Pull request by jessemapel**
That repo is now internal and likely will be replaced with something else once we have the SpiceQL service sorted out.

### CODE REVIEW

**Comment by jessemapel** [comment]
Fixes #376

**Comment by oleg-alexandrov** [comment]
Never have I seen such massive failure only as the result of some tiny doc text being added!

**Comment by jessemapel** [comment]
Something seems to have broken with our compiler compatibility. I'm looking into what happened.

**Comment by oleg-alexandrov** [comment]
I guess this can be pulled in as well. That dead link has been there for a while.

**Comment by jessemapel** [comment]
I'll get this rebased and re-check it before merging.

**Pull request merged**
