### PR TITLE
GXP supfile integration and tests

### LINKED ISSUE #400: GXP state file read (*.sup) added to test utility
background:
GXP saves camera state as a single string near the bottom of its' "sup" (supplement) file per image. The .sup is only created when a triangulation is initialized and again after each triangulation solve (bundle adjustment). Three new files have been uploaded to a gxp_testing branch to facilitate this issue (files ESP_037330*.*) : https://github.com/USGS-Astrogeology/usgscsm/tree/gxp_testing/tests/data 

1. Original ALE Image Support Data (ISD) in JSON format, [ESP_037330_1990_REDmos_hijitreged_ale.json](https://github.com/USGS-Astrogeology/usgscsm/blob/gxp_testing/tests/data/ESP_037330_1990_REDmos_hijitreged_ale.json)
2. GXP output for triangulation initialization (in GXP .sup format). [ESP_037330_1990_REDmos_hijitreged.preTriang.sup](https://github.com/USGS-Astrogeology/usgscsm/blob/gxp_testing/tests/data/ESP_037330_1990_REDmos_hijitreged.preTriang.sup)
3. GXP output from post triangulation adjustment (in GXP .sup format). [ESP_037330_1990_REDmos_hijitreged_postTriang.sup](https://github.com/USGS-Astrogeology/usgscsm/blob/gxp_testing/tests/data/ESP_037330_1990_REDmos_hijitreged_postTriang.sup)

From the .sup files, we are only interested in the SENSOR_STATE USGS_ASTRO_LINE_SCANNER_SENSOR_MODEL line. This again contains one giant camera state string. It seems to have an odd or special character "" which may need to stripped before attempting to load into usgscsm.

---

As a user I would like the usgscsm library to be able to parse a GXP .sup file to load the camera state.  The goal is to allow sharing between GXP and other CSM applications like ASP and ISIS. The usgscsm camera state would need to open GXP .sup file, recognize it is a GXP .sup file, find/parse the camera state line, and load it into usgscsm.

definition of done (being able to run):
`usgscsm_cam_test --model ESP_037330_1990_REDmos_hijitreged_postTriang.sup`

If loading is possible, then I would also like to see testing from within usgscsm test application (usgscsm_cam_test.cc). Examples for using the testing application are already available in the repo.

If it is not possible to load a camera state from a .sup file, please document the issues here. For example, is the camera state mangled or other issue.

This is currently a one-way street. We are not attempting to support writing camera state to a GXP .sup file (just reading).

Resources:
1. original test [stereo-pair](https://pdsimage2.wr.usgs.gov/pub/pigpen/CSM_stereo_testing_sets/HiRISE/Mars2020_Jezero_N_IAU_cub.zip), from [wiki](https://github.com/USGS-Astrogeology/usgscsm/wiki/CSM-Stereo-Testing-Examples).
2. Introduction to [usgscsm camera state](https://github.com/USGS-Astrogeology/usgscsm#camera-model-format-and-model-state)
3. Introduction to [ASP's camera state](https://stereopipeline.readthedocs.io/en/latest/examples.html#exporting-csm-model-state-after-bundle-adjustment-and-alignment) capabilities 
4. testing [docs](https://github.com/USGS-Astrogeology/usgscsm/blob/dev/docs/source/tools/usgscsm_cam_test.rst)

### PR DESCRIPTION
**Pull request by AustinSanders**
Closes #400

### CODE REVIEW

**Review by jessemapel — COMMENTED** [review]
Changes looks good, but the new functionality in the script needs to be tested. See the tests/CMakeLists.txt file for how we do these.

**Comment by jessemapel** [comment]
Also, how big is the .sup file? GitHub won't render it so I'm curious what the size of the file is.

**Comment by thareUSGS** [comment]
The current .sups are likely fairly large since they are HiRISE. So perhaps for the tests simply using a framer or maybe CTX. CTX states should only be ~40KB.

**Comment by jessemapel** [comment]
@thareUSGS @amystamile-usgs @AustinSanders what's the status on this?

**Comment by thareUSGS** [comment]
@jessemapel ooh I thought this was pulled in already.  I would be happy to see this capability merged. I don't think it has had extensively testing but I have tested the ASP updated "sup" file in GXP successfully. An initial test to update camera state from ASP into GXP.  The opposite direction was tested by Oleg in ASP. Taking camera state directly from a GXP "sup" file into ASP.

**Comment by jessemapel** [comment]
The problem with this PR is that it has no automated testing on it. It cannot be merged until there is automated testing added, so there's more work that needs to be done. Is there a plan to do that?

**Comment by thareUSGS** [comment]
@jessemapel I'm not sure what is needed for testing but there were updates to:
https://github.com/USGS-Astrogeology/usgscsm/pull/409/files#diff-525f51116b059e04f880e591aee61e45ed292c61e40b92e6d44a22f1103087ef
and
Not sure what the "hello" test is doing. Looks to be a stub for a test?
https://github.com/USGS-Astrogeology/usgscsm/pull/409/files#diff-8dd74769e65dadd96bbddce40388b7164ee3b2a40b9220b188b621bb3c1b0b9a

I can simply vouch that it would be great to have this completed (with tests) and merged. If it requires more work, then I am happy to try to get that supported somehow. Otherwise, I guess I can try to support the needed tests.

**Comment by AustinSanders** [comment]
@jessemapel I've been planning on taking care of this with continuous support, but I let it slip through the cracks so far.  I can spend a few hours this week writing tests.

**Comment by jessemapel** [comment]
There's not rush on getting this done. I was just peeling a release, so I wanted to check and see if there was a plan or if I should delay this. This can go into the end of the fiscal year clean-up work.

**Review by jessemapel — APPROVED** [review]
@AustinSanders If you're done adding stuff, this looks good to go now.

**Pull request merged**
