### PR TITLE
Added methods for computing linearized detector coordinates

### PR DESCRIPTION
**Pull request by jessemapel**
The plane methods would be needed for CPPS search instead of the generalized detector distance, but I left them in if we every want CPPS.

### CODE REVIEW

**Comment by jessemapel** [comment]
@acpaquette This should be good to go for the search implementation

**Comment by jessemapel** [comment]
[Implement CPPS computation](https://trello.com/c/ZTBqz9M2/11-implement-cpps-computation)

**Comment by acpaquette** [comment]
@jessemapel Did this get PR'd into the wrong branch?

**Comment by jessemapel** [comment]
@acpaquette looks like I did. I'll PR it into dev too

**Pull request merged**
